In [1]:
import pandas as pd

print("Pandas version:", pd.__version__)
print("CreatorBridge Data Pipeline Ready!")

Pandas version: 2.3.3
CreatorBridge Data Pipeline Ready!

In [2]:
import sys

print(sys.executable)

c:\Users\vaish\AppData\Local\Programs\Python\Python313\python.exe

In [1]:
import sys
import pandas as pd

print(sys.executable)
print("Pandas:", pd.__version__)

c:\Users\vaish\OneDrive\Desktop\CreatorBridge\.venv\Scripts\python.exe
Pandas: 3.0.6

In [2]:
import pandas as pd
import numpy as np

print("Data generation libraries ready!")

Data generation libraries ready!

In [3]:
creators = pd.DataFrame({
    "creator_id": range(1, 21),
    "creator_name": [
        "TechWithAman", "GameZoneIndia", "BeautyByRiya", "FitWithNeha",
        "FinanceSimplified", "FoodieRahul", "LearnWithPriya", "CodeWithArjun",
        "GadgetGuru", "GamingAdda", "GlowWithAnanya", "HealthyHabits",
        "MoneyMentor", "StreetFoodDiaries", "StudySmart", "TechTalks",
        "FitnessFusion", "KitchenStories", "CareerCoach", "DigitalDost"
    ],
    "category": [
        "Technology", "Gaming", "Beauty", "Fitness",
        "Finance", "Food", "Education", "Technology",
        "Technology", "Gaming", "Beauty", "Fitness",
        "Finance", "Food", "Education", "Technology",
        "Fitness", "Food", "Education", "Technology"
    ],
    "location": [
        "Mumbai", "Delhi", "Pune", "Bangalore",
        "Hyderabad", "Mumbai", "Pune", "Bangalore",
        "Delhi", "Mumbai", "Pune", "Hyderabad",
        "Bangalore", "Delhi", "Mumbai", "Pune",
        "Bangalore", "Hyderabad", "Delhi", "Mumbai"
    ],
    "language": [
        "Hindi", "Hindi", "Hindi", "English",
        "English", "Hindi", "English", "English",
        "Hindi", "Hindi", "Hindi", "English",
        "English", "Hindi", "English", "English",
        "English", "Hindi", "English", "Hindi"
    ]
})

creators.head()

   creator_id       creator_name    category   location language
0           1       TechWithAman  Technology     Mumbai    Hindi
1           2      GameZoneIndia      Gaming      Delhi    Hindi
2           3       BeautyByRiya      Beauty       Pune    Hindi
3           4        FitWithNeha     Fitness  Bangalore  English
4           5  FinanceSimplified     Finance  Hyderabad  English

In [4]:
channels = pd.DataFrame({
    "channel_id": range(1, 21),
    "creator_id": range(1, 21),
    "channel_name": creators["creator_name"],
    "subscribers": [
        850000, 620000, 410000, 275000, 520000,
        190000, 145000, 380000, 710000, 330000,
        265000, 175000, 460000, 125000, 210000,
        590000, 155000, 98000, 185000, 295000
    ],
    "total_views": [
        95000000, 68000000, 42000000, 31000000, 57000000,
        18000000, 14000000, 39000000, 82000000, 35000000,
        28000000, 19000000, 51000000, 12000000, 22000000,
        64000000, 16000000, 9000000, 20000000, 33000000
    ],
    "total_videos": [
        245, 310, 185, 160, 210,
        275, 190, 225, 280, 340,
        175, 150, 195, 230, 165,
        260, 205, 180, 145, 215
    ]
})

channels.head()

,channel_id,creator_id,channel_name,subscribers,total_views,total_videos
0,1,1,TechWithAman,850000,95000000,245
1,2,2,GameZoneIndia,620000,68000000,310
2,3,3,BeautyByRiya,410000,42000000,185
3,4,4,FitWithNeha,275000,31000000,160
4,5,5,FinanceSimplified,520000,57000000,210

In [5]:
np.random.seed(42)

video_rows = []

video_titles = [
    "Complete Guide for Beginners",
    "Top 10 Tips You Should Know",
    "My Honest Review",
    "Things Nobody Tells You",
    "Best Ideas for 2026"
]

video_types = ["Long-form", "Long-form", "Shorts", "Long-form", "Shorts"]

video_id = 1

for creator_id in range(1, 21):
    creator_category = creators.loc[
        creators["creator_id"] == creator_id, "category"
    ].iloc[0]

    for i in range(5):
        video_rows.append({
            "video_id": video_id,
            "channel_id": creator_id,
            "title": video_titles[i],
            "category": creator_category,
            "video_type": video_types[i],
            "upload_date": pd.Timestamp("2026-01-01") + pd.Timedelta(
                days=int(np.random.randint(1, 270))
            ),
            "duration_minutes": (
                round(np.random.uniform(8, 25), 2)
                if video_types[i] == "Long-form"
                else round(np.random.uniform(0.3, 2), 2)
            )
        })

        video_id += 1

videos = pd.DataFrame(video_rows)

videos.head()

,video_id,channel_id,title,category,video_type,upload_date,duration_minutes
0,1,1,Complete Guide for Beginners,Technology,Long-form,2026-04-14,21.54
1,2,1,Top 10 Tips You Should Know,Technology,Long-form,2026-04-18,21.25
2,3,1,My Honest Review,Technology,Shorts,2026-01-22,0.57
3,4,1,Things Nobody Tells You,Technology,Long-form,2026-08-04,8.99
4,5,1,Best Ideas for 2026,Technology,Shorts,2026-03-30,0.87

In [ ]:
np.random.seed(42)

video_metrics = videos[["video_id"]].copy()

video_metrics["views"] = np.random.randint(
    10000, 2000000, size=len(videos)
)

video_metrics["likes"] = (
    video_metrics["views"] * np.random.uniform(0.02, 0.10, len(videos))
).astype(int)

video_metrics["comments"] = (
    video_metrics["views"] * np.random.uniform(0.001, 0.015, len(videos))
).astype(int)

video_metrics["shares"] = (
    video_metrics["views"] * np.random.uniform(0.001, 0.01, len(videos))
).astype(int)

video_metrics["watch_time_hours"] = (
    video_metrics["views"] *
    videos["duration_minutes"] *
    np.random.uniform(0.25, 0.65, len(videos))
    / 60
).round(2)

video_metrics.head()

In [6]:
np.random.seed(42)

video_metrics = videos[["video_id"]].copy()

video_metrics["views"] = np.random.randint(
    10000, 2000000, size=len(videos)
)

video_metrics["likes"] = (
    video_metrics["views"] * np.random.uniform(0.02, 0.10, len(videos))
).astype(int)

video_metrics["comments"] = (
    video_metrics["views"] * np.random.uniform(0.001, 0.015, len(videos))
).astype(int)

video_metrics["shares"] = (
    video_metrics["views"] * np.random.uniform(0.001, 0.01, len(videos))
).astype(int)

video_metrics["watch_time_hours"] = (
    video_metrics["views"] *
    videos["duration_minutes"] *
    np.random.uniform(0.25, 0.65, len(videos))
    / 60
).round(2)

video_metrics.head()

   video_id    views   likes  comments  shares  watch_time_hours
0         1   131958   12557       399    1142          24324.93
1         2   681155   62384      5348    2624          76033.28
2         3   141932    9627      2100     358            375.15
3         4  1424414  133538      6251    8562         108199.43
4         5   269178    7289      2802    2537           1017.16

In [7]:
np.random.seed(42)

audience_rows = []

age_groups = ["18-24", "25-34", "35-44", "45+"]
genders = ["Male", "Female"]

audience_id = 1

for channel_id in range(1, 21):
    for age_group in age_groups:
        for gender in genders:
            audience_rows.append({
                "audience_id": audience_id,
                "channel_id": channel_id,
                "age_group": age_group,
                "gender": gender,
                "location": creators.loc[
                    creators["creator_id"] == channel_id, "location"
                ].iloc[0],
                "audience_percentage": round(
                    np.random.uniform(2, 20), 2
                )
            })

            audience_id += 1

audience = pd.DataFrame(audience_rows)

audience.head()

   audience_id  channel_id age_group  gender location  audience_percentage
0            1           1     18-24    Male   Mumbai                 8.74
1            2           1     18-24  Female   Mumbai                19.11
2            3           1     25-34    Male   Mumbai                15.18
3            4           1     25-34  Female   Mumbai                12.78
4            5           1     35-44    Male   Mumbai                 4.81

In [8]:
brands = pd.DataFrame({
    "brand_id": range(1, 11),
    "brand_name": [
        "TechNova", "GlowCare", "FitLife", "MoneyWise",
        "FoodFusion", "LearnPro", "GameX", "StyleSphere",
        "GadgetWorld", "HealthPlus"
    ],
    "category": [
        "Technology", "Beauty", "Fitness", "Finance",
        "Food", "Education", "Gaming", "Beauty",
        "Technology", "Fitness"
    ],
    "product": [
        "Smartphone", "Skincare Kit", "Fitness Tracker", "Investment App",
        "Snack Box", "Online Course", "Gaming Headset", "Makeup Kit",
        "Wireless Earbuds", "Protein Supplement"
    ]
})

brands.head()

   brand_id  brand_name    category          product
0         1    TechNova  Technology       Smartphone
1         2    GlowCare      Beauty     Skincare Kit
2         3     FitLife     Fitness  Fitness Tracker
3         4   MoneyWise     Finance   Investment App
4         5  FoodFusion        Food        Snack Box

In [9]:
campaigns = pd.DataFrame({
    "campaign_id": range(1, 16),
    "brand_id": [
        1, 2, 3, 4, 5,
        6, 7, 8, 9, 10,
        1, 3, 4, 7, 9
    ],
    "campaign_name": [
        "Smartphone Launch",
        "Glow Up Campaign",
        "Fitness Challenge",
        "Invest Smart",
        "Snack & Share",
        "Learn Better",
        "Level Up Gaming",
        "Beauty Essentials",
        "Audio Upgrade",
        "Healthy Lifestyle",
        "Next Gen Phone",
        "Summer Fitness",
        "Finance Awareness",
        "Gaming Fest",
        "Tech Accessories"
    ],
    "product": [
        "Smartphone", "Skincare Kit", "Fitness Tracker",
        "Investment App", "Snack Box", "Online Course",
        "Gaming Headset", "Makeup Kit", "Wireless Earbuds",
        "Protein Supplement", "Smartphone", "Fitness Tracker",
        "Investment App", "Gaming Headset", "Wireless Earbuds"
    ],
    "campaign_category": [
        "Technology", "Beauty", "Fitness", "Finance", "Food",
        "Education", "Gaming", "Beauty", "Technology", "Fitness",
        "Technology", "Fitness", "Finance", "Gaming", "Technology"
    ],
    "budget": [
        250000, 180000, 150000, 220000, 100000,
        120000, 200000, 140000, 175000, 130000,
        300000, 160000, 190000, 225000, 210000
    ],
    "start_date": pd.date_range("2026-01-10", periods=15, freq="20D"),
    "end_date": pd.date_range("2026-01-24", periods=15, freq="20D")
})

campaigns.head()

,campaign_id,brand_id,campaign_name,product,campaign_category,budget,start_date,end_date
0,1,1,Smartphone Launch,Smartphone,Technology,250000,2026-01-10,2026-01-24
1,2,2,Glow Up Campaign,Skincare Kit,Beauty,180000,2026-01-30,2026-02-13
2,3,3,Fitness Challenge,Fitness Tracker,Fitness,150000,2026-02-19,2026-03-05
3,4,4,Invest Smart,Investment App,Finance,220000,2026-03-11,2026-03-25
4,5,5,Snack & Share,Snack Box,Food,100000,2026-03-31,2026-04-14

In [10]:
np.random.seed(42)

campaign_creator_rows = []

for campaign_id in campaigns["campaign_id"]:
    campaign_category = campaigns.loc[
        campaigns["campaign_id"] == campaign_id,
        "campaign_category"
    ].iloc[0]

    matching_creators = creators[
        creators["category"] == campaign_category
    ]["creator_id"].tolist()

    selected_creators = np.random.choice(
        matching_creators,
        size=min(3, len(matching_creators)),
        replace=False
    )

    for creator_id in selected_creators:
        campaign_budget = campaigns.loc[
            campaigns["campaign_id"] == campaign_id,
            "budget"
        ].iloc[0]

        campaign_creator_rows.append({
            "campaign_id": campaign_id,
            "creator_id": int(creator_id),
            "agreed_cost": round(
                campaign_budget * np.random.uniform(0.15, 0.35), 2
            )
        })

campaign_creators = pd.DataFrame(campaign_creator_rows)

campaign_creators.head()

   campaign_id  creator_id  agreed_cost
0            1           8     76484.55
1            1          20     67342.51
2            1           9     59791.64
3            2          11     29091.01
4            2           3     58182.34

In [11]:
np.random.seed(42)

performance_rows = []

for _, row in campaign_creators.iterrows():

    views = np.random.randint(50000, 1000000)

    likes = int(views * np.random.uniform(0.03, 0.10))
    comments = int(views * np.random.uniform(0.001, 0.015))
    clicks = int(views * np.random.uniform(0.01, 0.08))
    conversions = int(clicks * np.random.uniform(0.03, 0.15))

    revenue = round(
        conversions * np.random.uniform(500, 3000),
        2
    )

    performance_rows.append({
        "campaign_id": row["campaign_id"],
        "creator_id": row["creator_id"],
        "views": views,
        "likes": likes,
        "comments": comments,
        "clicks": clicks,
        "conversions": conversions,
        "revenue": revenue
    })

campaign_performance = pd.DataFrame(performance_rows)

campaign_performance.head()

,campaign_id,creator_id,views,likes,comments,clicks,conversions,revenue
0,1.0,8.0,171958,14746,613,11104,1128,1821248.36
1,1.0,20.0,571430,19466,7500,29758,3421,1886548.89
2,1.0,9.0,837201,67428,11837,8417,1254,2562804.53
3,2.0,11.0,397449,26522,2800,12076,1248,1059220.85
4,2.0,3.0,704811,69186,3001,11518,1200,1747385.97

In [12]:
import os

os.makedirs("../data/generated", exist_ok=True)

creators.to_csv("../data/generated/creators.csv", index=False)
channels.to_csv("../data/generated/channels.csv", index=False)
videos.to_csv("../data/generated/videos.csv", index=False)
video_metrics.to_csv("../data/generated/video_metrics.csv", index=False)
audience.to_csv("../data/generated/audience.csv", index=False)
brands.to_csv("../data/generated/brands.csv", index=False)
campaigns.to_csv("../data/generated/campaigns.csv", index=False)
campaign_creators.to_csv("../data/generated/campaign_creators.csv", index=False)
campaign_performance.to_csv("../data/generated/campaign_performance.csv", index=False)

print("All CSV files exported successfully!")

All CSV files exported successfully!

In [1]:
# CreatorBridge - Basic Data Validation

print("=== CreatorBridge Data Validation ===")

datasets = {
    "Creators": creators,
    "Channels": channels,
    "Videos": videos,
    "Video Metrics": video_metrics,
    "Audience": audience,
    "Brands": brands,
    "Campaigns": campaigns,
    "Campaign Creators": campaign_creators,
    "Campaign Performance": campaign_performance
}

for name, df in datasets.items():
    print(f"{name:25} Rows: {len(df):4} | Columns: {len(df.columns):2}")

=== CreatorBridge Data Validation ===

NameError: name 'creators' is not defined

In [2]:
import pandas as pd
import os

data_path = "../data/generated"

creators = pd.read_csv(f"{data_path}/creators.csv")
channels = pd.read_csv(f"{data_path}/channels.csv")
videos = pd.read_csv(f"{data_path}/videos.csv")
video_metrics = pd.read_csv(f"{data_path}/video_metrics.csv")
audience = pd.read_csv(f"{data_path}/audience.csv")
brands = pd.read_csv(f"{data_path}/brands.csv")
campaigns = pd.read_csv(f"{data_path}/campaigns.csv")
campaign_creators = pd.read_csv(f"{data_path}/campaign_creators.csv")
campaign_performance = pd.read_csv(f"{data_path}/campaign_performance.csv")

print("CreatorBridge datasets loaded successfully! ✅")

CreatorBridge datasets loaded successfully! ✅

In [3]:
datasets = {
    "Creators": creators,
    "Channels": channels,
    "Videos": videos,
    "Video Metrics": video_metrics,
    "Audience": audience,
    "Brands": brands,
    "Campaigns": campaigns,
    "Campaign Creators": campaign_creators,
    "Campaign Performance": campaign_performance
}

print("=== CreatorBridge Dataset Summary ===")

for name, df in datasets.items():
    print(f"{name:25} Rows: {len(df):4} | Columns: {len(df.columns):2}")

=== CreatorBridge Dataset Summary ===
Creators                  Rows:   20 | Columns:  5
Channels                  Rows:   20 | Columns:  6
Videos                    Rows:  100 | Columns:  7
Video Metrics             Rows:  100 | Columns:  6
Audience                  Rows:  160 | Columns:  6
Brands                    Rows:   10 | Columns:  4
Campaigns                 Rows:   15 | Columns:  8
Campaign Creators         Rows:   39 | Columns:  3
Campaign Performance      Rows:   39 | Columns:  8

In [4]:
for name, df in datasets.items():
    print(f"\n--- {name} ---")
    print("Missing values:", df.isnull().sum().sum())
    print("Duplicate rows:", df.duplicated().sum())

--- Creators ---
Missing values: 0
Duplicate rows: 0

--- Channels ---
Missing values: 0
Duplicate rows: 0

--- Videos ---
Missing values: 0
Duplicate rows: 0

--- Video Metrics ---
Missing values: 0
Duplicate rows: 0

--- Audience ---
Missing values: 0
Duplicate rows: 0

--- Brands ---
Missing values: 0
Duplicate rows: 0

--- Campaigns ---
Missing values: 0
Duplicate rows: 0

--- Campaign Creators ---
Missing values: 0
Duplicate rows: 0

--- Campaign Performance ---
Missing values: 0
Duplicate rows: 0

In [5]:
audience_check = (
    audience
    .groupby("channel_id")["audience_percentage"]
    .sum()
    .reset_index()
)

print(audience_check)

    channel_id  audience_percentage
0            1                86.07
1            2                82.77
2            3                69.32
3            4                76.70
4            5                93.66
5            6                75.66
6            7               120.94
7            8                61.01
8            9                84.39
9           10                80.37
10          11                85.92
11          12               102.02
12          13                62.35
13          14                71.45
14          15               117.98
15          16                96.36
16          17                67.86
17          18                98.25
18          19                68.42
19          20                92.72

In [6]:
audience["audience_percentage"] = (
    audience.groupby("channel_id")["audience_percentage"]
    .transform(lambda x: x / x.sum() * 100)
    .round(2)
)

print(
    audience.groupby("channel_id")["audience_percentage"]
    .sum()
)

channel_id
1     100.00
2      99.99
3     100.00
4     100.00
5      99.99
6      99.99
7     100.00
8      99.99
9     100.01
10     99.99
11    100.00
12    100.00
13    100.01
14     99.99
15    100.01
16     99.99
17     99.99
18    100.00
19    100.00
20    100.00
Name: audience_percentage, dtype: float64

In [7]:
invalid_campaigns = campaign_performance[
    (campaign_performance["clicks"] > campaign_performance["views"]) |
    (campaign_performance["conversions"] > campaign_performance["clicks"])
]

print("Invalid campaign performance records:", len(invalid_campaigns))

invalid_campaigns

Invalid campaign performance records: 0

Empty DataFrame
Columns: [campaign_id, creator_id, views, likes, comments, clicks, conversions, revenue]
Index: []

In [8]:
invalid_channels = channels[
    ~channels["creator_id"].isin(creators["creator_id"])
]

print("Invalid channel-creator relationships:", len(invalid_channels))

invalid_channels

Invalid channel-creator relationships: 0

Empty DataFrame
Columns: [channel_id, creator_id, channel_name, subscribers, total_views, total_videos]
Index: []

In [9]:
invalid_videos = videos[
    ~videos["channel_id"].isin(channels["channel_id"])
]

print("Invalid video-channel relationships:", len(invalid_videos))

invalid_videos

Invalid video-channel relationships: 0

Empty DataFrame
Columns: [video_id, channel_id, title, category, video_type, upload_date, duration_minutes]
Index: []

In [10]:
invalid_metrics = video_metrics[
    ~video_metrics["video_id"].isin(videos["video_id"])
]

print("Invalid video-metrics relationships:", len(invalid_metrics))

invalid_metrics

Invalid video-metrics relationships: 0

Empty DataFrame
Columns: [video_id, views, likes, comments, shares, watch_time_hours]
Index: []

In [11]:
invalid_campaign_links = campaign_creators[
    ~campaign_creators["campaign_id"].isin(campaigns["campaign_id"])
]

print("Invalid campaign relationships:", len(invalid_campaign_links))

invalid_campaign_links

Invalid campaign relationships: 0

Empty DataFrame
Columns: [campaign_id, creator_id, agreed_cost]
Index: []

In [12]:
invalid_creator_links = campaign_creators[
    ~campaign_creators["creator_id"].isin(creators["creator_id"])
]

print("Invalid campaign-creator relationships:", len(invalid_creator_links))

invalid_creator_links

Invalid campaign-creator relationships: 0

Empty DataFrame
Columns: [campaign_id, creator_id, agreed_cost]
Index: []

In [1]:
# Load the creator-level datasets for scoring

creators = pd.read_csv("../data/generated/creators.csv")
channels = pd.read_csv("../data/generated/channels.csv")
videos = pd.read_csv("../data/generated/videos.csv")
video_metrics = pd.read_csv("../data/generated/video_metrics.csv")

print("Scoring datasets loaded successfully! ✅")

NameError: name 'pd' is not defined

In [2]:
# Load the creator-level datasets for scoring

creators = pd.read_csv("../data/generated/creators.csv")
channels = pd.read_csv("../data/generated/channels.csv")
videos = pd.read_csv("../data/generated/videos.csv")
video_metrics = pd.read_csv("../data/generated/video_metrics.csv")

print("Scoring datasets loaded successfully! ✅")

NameError: name 'pd' is not defined

In [3]:
import pandas as pd

In [4]:
creators = pd.read_csv("../data/generated/creators.csv")
channels = pd.read_csv("../data/generated/channels.csv")
videos = pd.read_csv("../data/generated/videos.csv")
video_metrics = pd.read_csv("../data/generated/video_metrics.csv")

print("Scoring datasets loaded successfully! ✅")

Scoring datasets loaded successfully! ✅

In [5]:
creator_base = creators.merge(
    channels,
    on="creator_id",
    how="inner"
)

print("Creator base created successfully! ✅")
print(creator_base.head())

Creator base created successfully! ✅
   creator_id       creator_name    category   location language  channel_id  \
0           1       TechWithAman  Technology     Mumbai    Hindi           1
1           2      GameZoneIndia      Gaming      Delhi    Hindi           2
2           3       BeautyByRiya      Beauty       Pune    Hindi           3
3           4        FitWithNeha     Fitness  Bangalore  English           4
4           5  FinanceSimplified     Finance  Hyderabad  English           5

        channel_name  subscribers  total_views  total_videos
0       TechWithAman       850000     95000000           245
1      GameZoneIndia       620000     68000000           310
2       BeautyByRiya       410000     42000000           185
3        FitWithNeha       275000     31000000           160
4  FinanceSimplified       520000     57000000           210

In [6]:
creator_base["avg_views_per_video"] = (
    creator_base["total_views"] / creator_base["total_videos"]
).round(0)

print(creator_base[
    ["creator_name", "subscribers", "avg_views_per_video"]
].head(10))

        creator_name  subscribers  avg_views_per_video
0       TechWithAman       850000             387755.0
1      GameZoneIndia       620000             219355.0
2       BeautyByRiya       410000             227027.0
3        FitWithNeha       275000             193750.0
4  FinanceSimplified       520000             271429.0
5        FoodieRahul       190000              65455.0
6     LearnWithPriya       145000              73684.0
7      CodeWithArjun       380000             173333.0
8         GadgetGuru       710000             292857.0
9         GamingAdda       330000             102941.0

In [7]:
video_data = videos.merge(
    video_metrics,
    on="video_id",
    how="inner"
)

creator_engagement = (
    video_data
    .merge(
        channels[["channel_id", "creator_id"]],
        on="channel_id",
        how="inner"
    )
    .groupby("creator_id")
    .agg(
        total_video_views=("views", "sum"),
        total_likes=("likes", "sum"),
        total_comments=("comments", "sum")
    )
    .reset_index()
)

creator_engagement["engagement_rate"] = (
    (creator_engagement["total_likes"] +
     creator_engagement["total_comments"])
    / creator_engagement["total_video_views"] * 100
).round(2)

print(creator_engagement.head(10))

   creator_id  total_video_views  total_likes  total_comments  engagement_rate
0           1            2648637       225395           16900             9.15
1           2            3825990       160786           36983             5.17
2           3            6616461       365533           55909             6.37
3           4            2113736        92915            6256             4.69
4           5            5415012       363291           36062             7.37
5           6            5302660       232790           35872             5.07
6           7            5353477       273580           54412             6.13
7           8            4466135       251181           25648             6.20
8           9            5782668       421121           57339             8.27
9          10            3528021       104603           42178             4.16

In [8]:
creator_base = creator_base.merge(
    creator_engagement[
        ["creator_id", "total_video_views", "total_likes",
         "total_comments", "engagement_rate"]
    ],
    on="creator_id",
    how="left"
)

print(
    creator_base[
        [
            "creator_name",
            "subscribers",
            "avg_views_per_video",
            "engagement_rate"
        ]
    ].head(10)
)

        creator_name  subscribers  avg_views_per_video  engagement_rate
0       TechWithAman       850000             387755.0             9.15
1      GameZoneIndia       620000             219355.0             5.17
2       BeautyByRiya       410000             227027.0             6.37
3        FitWithNeha       275000             193750.0             4.69
4  FinanceSimplified       520000             271429.0             7.37
5        FoodieRahul       190000              65455.0             5.07
6     LearnWithPriya       145000              73684.0             6.13
7      CodeWithArjun       380000             173333.0             6.20
8         GadgetGuru       710000             292857.0             8.27
9         GamingAdda       330000             102941.0             4.16

In [9]:
creator_base["views_score"] = (
    creator_base["avg_views_per_video"]
    / creator_base["avg_views_per_video"].max()
    * 100
).round(2)

print(
    creator_base[
        ["creator_name", "avg_views_per_video", "views_score"]
    ].sort_values("views_score", ascending=False).head(10)
)

         creator_name  avg_views_per_video  views_score
0        TechWithAman             387755.0       100.00
8          GadgetGuru             292857.0        75.53
4   FinanceSimplified             271429.0        70.00
12        MoneyMentor             261538.0        67.45
15          TechTalks             246154.0        63.48
2        BeautyByRiya             227027.0        58.55
1       GameZoneIndia             219355.0        56.57
3         FitWithNeha             193750.0        49.97
7       CodeWithArjun             173333.0        44.70
10     GlowWithAnanya             160000.0        41.26

In [10]:
creator_base["engagement_score"] = (
    creator_base["engagement_rate"]
    / creator_base["engagement_rate"].max()
    * 100
).round(2)

print(
    creator_base[
        ["creator_name", "engagement_rate", "engagement_score"]
    ].sort_values("engagement_score", ascending=False).head(10)
)

         creator_name  engagement_rate  engagement_score
0        TechWithAman             9.15            100.00
12        MoneyMentor             8.96             97.92
13  StreetFoodDiaries             8.78             95.96
8          GadgetGuru             8.27             90.38
17     KitchenStories             8.07             88.20
4   FinanceSimplified             7.37             80.55
19        DigitalDost             6.94             75.85
16      FitnessFusion             6.60             72.13
10     GlowWithAnanya             6.56             71.69
2        BeautyByRiya             6.37             69.62

In [11]:
creator_base["subscriber_score"] = (
    creator_base["subscribers"]
    / creator_base["subscribers"].max()
    * 100
).round(2)

print(
    creator_base[
        ["creator_name", "subscribers", "subscriber_score"]
    ].sort_values("subscriber_score", ascending=False).head(10)
)

         creator_name  subscribers  subscriber_score
0        TechWithAman       850000            100.00
8          GadgetGuru       710000             83.53
1       GameZoneIndia       620000             72.94
15          TechTalks       590000             69.41
4   FinanceSimplified       520000             61.18
12        MoneyMentor       460000             54.12
2        BeautyByRiya       410000             48.24
7       CodeWithArjun       380000             44.71
9          GamingAdda       330000             38.82
19        DigitalDost       295000             34.71

In [12]:
creator_base["creator_performance_score"] = (
    creator_base["engagement_score"] * 0.40
    + creator_base["views_score"] * 0.35
    + creator_base["subscriber_score"] * 0.25
).round(2)

print(
    creator_base[
        [
            "creator_name",
            "category",
            "views_score",
            "engagement_score",
            "subscriber_score",
            "creator_performance_score"
        ]
    ]
    .sort_values("creator_performance_score", ascending=False)
    .head(10)
)

         creator_name    category  views_score  engagement_score  \
0        TechWithAman  Technology       100.00            100.00
8          GadgetGuru  Technology        75.53             90.38
12        MoneyMentor     Finance        67.45             97.92
4   FinanceSimplified     Finance        70.00             80.55
15          TechTalks  Technology        63.48             60.66
1       GameZoneIndia      Gaming        56.57             56.50
2        BeautyByRiya      Beauty        58.55             69.62
7       CodeWithArjun  Technology        44.70             67.76
19        DigitalDost  Technology        39.58             75.85
10     GlowWithAnanya      Beauty        41.26             71.69

    subscriber_score  creator_performance_score
0             100.00                     100.00
8              83.53                      83.47
12             54.12                      76.31
4              61.18                      72.02
15             69.41                      63.83
1              72.94                      60.63
2              48.24                      60.40
7              44.71                      53.93
19             34.71                      52.87
10             31.18                      50.91

In [13]:
creator_score = creator_base[
    [
        "creator_id",
        "creator_name",
        "category",
        "location",
        "language",
        "subscribers",
        "avg_views_per_video",
        "engagement_rate",
        "creator_performance_score"
    ]
].sort_values(
    "creator_performance_score",
    ascending=False
)

creator_score.to_csv(
    "../data/generated/creator_performance_score.csv",
    index=False
)

print("Creator performance score saved successfully! ✅")

Creator performance score saved successfully! ✅

In [14]:
campaign_creators = pd.read_csv(
    "../data/generated/campaign_creators.csv"
)

campaign_performance = pd.read_csv(
    "../data/generated/campaign_performance.csv"
)

print("Campaign datasets loaded successfully! ✅")

Campaign datasets loaded successfully! ✅

In [15]:
creator_campaign = campaign_creators.merge(
    campaign_performance,
    on=["campaign_id", "creator_id"],
    how="inner"
)

print(creator_campaign.head())

   campaign_id  creator_id  agreed_cost   views  likes  comments  clicks  \
0            1           8     76484.55  171958  14746       613   11104
1            1          20     67342.51  571430  19466      7500   29758
2            1           9     59791.64  837201  67428     11837    8417
3            2          11     29091.01  397449  26522      2800   12076
4            2           3     58182.34  704811  69186      3001   11518

   conversions     revenue
0         1128  1821248.36
1         3421  1886548.89
2         1254  2562804.53
3         1248  1059220.85
4         1200  1747385.97

In [16]:
campaign_summary = (
    creator_campaign
    .groupby("creator_id")
    .agg(
        total_campaigns=("campaign_id", "nunique"),
        campaign_views=("views", "sum"),
        campaign_clicks=("clicks", "sum"),
        campaign_conversions=("conversions", "sum"),
        campaign_revenue=("revenue", "sum"),
        campaign_cost=("agreed_cost", "sum")
    )
    .reset_index()
)

print(campaign_summary.head(10))

   creator_id  total_campaigns  campaign_views  campaign_clicks  \
0           1                3         1944335           108619
1           2                2         1465085            96987
2           3                2          860689            15292
3           4                3         1519330            69103
4           5                2          631632            30631
5           6                1          585822             7712
6           7                1          698663            41775
7           8                3         1504044            96191
8           9                2          964706            11693
9          10                2         1722790           110054

   campaign_conversions  campaign_revenue  campaign_cost
0                  8753        7829347.49      146639.59
1                 10782       23667136.29      115395.98
2                  1740        2825854.35       92251.70
3                  6112       12718059.24      101884.75
4                  3085        3017895.72       76524.77
5                   532         782940.80       15141.33
6                  5214       10505688.27       19119.98
7                  9861       22913343.27      165565.33
8                  1632        2976004.92      113166.68
9                  9402       14428469.36       89518.71

In [17]:
campaign_summary["campaign_conversion_rate"] = (
    campaign_summary["campaign_conversions"]
    / campaign_summary["campaign_clicks"]
    * 100
).round(2)

print(
    campaign_summary[
        [
            "creator_id",
            "campaign_clicks",
            "campaign_conversions",
            "campaign_conversion_rate"
        ]
    ].sort_values(
        "campaign_conversion_rate",
        ascending=False
    ).head(10)
)

    creator_id  campaign_clicks  campaign_conversions  \
8            9            11693                  1632
12          13            66653                  8777
6            7            41775                  5214
13          14            48424                  5940
2            3            15292                  1740
1            2            96987                 10782
14          15            13001                  1362
17          18            40124                  4126
7            8            96191                  9861
18          19            22718                  2293

    campaign_conversion_rate
8                      13.96
12                     13.17
6                      12.48
13                     12.27
2                      11.38
1                      11.12
14                     10.48
17                     10.28
7                      10.25
18                     10.09

In [18]:
campaign_summary["campaign_score"] = (
    campaign_summary["campaign_conversion_rate"]
    / campaign_summary["campaign_conversion_rate"].max()
    * 100
).round(2)

print(
    campaign_summary[
        [
            "creator_id",
            "campaign_conversion_rate",
            "campaign_score"
        ]
    ].sort_values(
        "campaign_score",
        ascending=False
    ).head(10)
)

    creator_id  campaign_conversion_rate  campaign_score
8            9                     13.96          100.00
12          13                     13.17           94.34
6            7                     12.48           89.40
13          14                     12.27           87.89
2            3                     11.38           81.52
1            2                     11.12           79.66
14          15                     10.48           75.07
17          18                     10.28           73.64
7            8                     10.25           73.42
18          19                     10.09           72.28

In [19]:
creator_base = creator_base.merge(
    campaign_summary[
        [
            "creator_id",
            "total_campaigns",
            "campaign_views",
            "campaign_clicks",
            "campaign_conversions",
            "campaign_revenue",
            "campaign_cost",
            "campaign_conversion_rate",
            "campaign_score"
        ]
    ],
    on="creator_id",
    how="left"
)

print(
    creator_base[
        [
            "creator_name",
            "creator_performance_score",
            "campaign_conversion_rate",
            "campaign_score"
        ]
    ].head(10)
)

        creator_name  creator_performance_score  campaign_conversion_rate  \
0       TechWithAman                     100.00                      8.06
1      GameZoneIndia                      60.63                     11.12
2       BeautyByRiya                      60.40                     11.38
3        FitWithNeha                      46.08                      8.84
4  FinanceSimplified                      72.02                     10.07
5        FoodieRahul                      33.66                      6.90
6     LearnWithPriya                      37.71                     12.48
7      CodeWithArjun                      53.93                     10.25
8         GadgetGuru                      83.47                     13.96
9         GamingAdda                      37.18                      8.54

   campaign_score
0           57.74
1           79.66
2           81.52
3           63.32
4           72.13
5           49.43
6           89.40
7           73.42
8          100.00
9           61.17

In [20]:
creator_base["creatorbridge_score"] = (
    creator_base["creator_performance_score"] * 0.70
    + creator_base["campaign_score"] * 0.30
).round(2)

print(
    creator_base[
        [
            "creator_name",
            "category",
            "creator_performance_score",
            "campaign_score",
            "creatorbridge_score"
        ]
    ]
    .sort_values(
        "creatorbridge_score",
        ascending=False
    )
    .head(10)
)

         creator_name    category  creator_performance_score  campaign_score  \
8          GadgetGuru  Technology                      83.47          100.00
0        TechWithAman  Technology                     100.00           57.74
12        MoneyMentor     Finance                      76.31           94.34
4   FinanceSimplified     Finance                      72.02           72.13
2        BeautyByRiya      Beauty                      60.40           81.52
1       GameZoneIndia      Gaming                      60.63           79.66
15          TechTalks  Technology                      63.83           58.17
7       CodeWithArjun  Technology                      53.93           73.42
13  StreetFoodDiaries        Food                      46.77           87.89
10     GlowWithAnanya      Beauty                      50.91           70.06

    creatorbridge_score
8                 88.43
0                 87.32
12                81.72
4                 72.05
2                 66.74
1                 66.34
15                62.13
7                 59.78
13                59.11
10                56.65

In [21]:
final_creator_scores = creator_base[
    [
        "creator_id",
        "creator_name",
        "category",
        "location",
        "language",
        "subscribers",
        "avg_views_per_video",
        "engagement_rate",
        "total_campaigns",
        "campaign_views",
        "campaign_clicks",
        "campaign_conversions",
        "campaign_conversion_rate",
        "creator_performance_score",
        "campaign_score",
        "creatorbridge_score"
    ]
].sort_values(
    "creatorbridge_score",
    ascending=False
)

final_creator_scores.to_csv(
    "../data/generated/final_creator_scores.csv",
    index=False
)

print("Final CreatorBridge scores saved successfully! ✅")

Final CreatorBridge scores saved successfully! ✅

In [22]:
print(final_creator_scores.shape)

(20, 16)